import { Switch } from '@nd/core/models';

export const lights: Switch[] = [
  {
    'AddjMulti': 1,
    'AddjMulti2': 1,
    'AddjValue': 0,
    'AddjValue2': 0,
    'BatteryLevel': 255,
    'CustomImage': 10,
    'Data': 'Off',
    'Description': '',
    'DimmerType': 'none',
    'Favorite': 1,
    'HardwareID': 3,
    'HardwareName': 'Z-Wave',
    'HardwareType': 'OpenZWave USB',
    'HardwareTypeVal': 21,
    'HaveDimmer': true,
    'HaveGroupCmd': true,
    'HaveTimeout': false,
    'ID': '00000401',
    'Image': 'Fireplace',
    'IsSubDevice': false,
    'LastUpdate': '2019-04-06 11:33:36',
    'Level': 0,
    'LevelInt': 0,
    'MaxDimLevel': 100,
    'Name': 'Fireplace bedroom 1',
    'Notifications': 'false',
    'PlanID': '0',
    'PlanIDs': [
      0
    ],
    'Protected': false,
    'ShowNotifications': true,
    'SignalLevel': '-',
    'Status': 'Off',
    'StrParam1': '',
    'StrParam2': '',
    'SubType': 'Switch',
    'SwitchType': 'On/Off',
    'SwitchTypeVal': 0,
    'Timers': 'false',
    'Type': 'Light/Switch',
    'TypeImg': 'lightbulb',
    'Unit': 1,
    'Used': 1,
    'UsedByCamera': false,
    'XOffset': '0',
    'YOffset': '0',
    'idx': '14'
  },
  {
    'AddjMulti': 1,
    'AddjMulti2': 1,
    'AddjValue': 0,
    'AddjValue2': 0,
    'BatteryLevel': 255,
    'CustomImage': 10,
    'Data': 'Off',
    'Description': '',
    'DimmerType': 'none',
    'Favorite': 1,
    'HardwareID': 3,
    'HardwareName': 'Z-Wave',
    'HardwareType': 'OpenZWave USB',
    'HardwareTypeVal': 21,
    'HaveDimmer': true,
    'HaveGroupCmd': true,
    'HaveTimeout': false,
    'ID': '00000501',
    'Image': 'Fireplace',
    'IsSubDevice': false,
    'LastUpdate': '2019-04-06 14:10:16',
    'Level': 0,
    'LevelInt': 0,
    'MaxDimLevel': 100,
    'Name': 'Fireplace living room',
    'Notifications': 'false',
    'PlanID': '0',
    'PlanIDs': [
      0
    ],
    'Protected': false,
    'ShowNotifications': true,
    'SignalLevel': '-',
    'Status': 'Off',
    'StrParam1': '',
    'StrParam2': '',
    'SubType': 'Switch',
    'SwitchType': 'On/Off',
    'SwitchTypeVal': 0,
    'Timers': 'false',
    'Type': 'Light/Switch',
    'TypeImg': 'lightbulb',
    'Unit': 1,
    'Used': 1,
    'UsedByCamera': false,
    'XOffset': '0',
    'YOffset': '0',
    'idx': '32'
  },
  {
    'AddjMulti': 1,
    'AddjMulti2': 1,
    'AddjValue': 0,
    'AddjValue2': 0,
    'BatteryLevel': 92,
    'CustomImage': 0,
    'Data': 'Closed',
    'Description': '',
    'DimmerType': 'none',
    'Favorite': 1,
    'HardwareID': 4,
    'HardwareName': 'Zigate',
    'HardwareType': 'Zigate plugin',
    'HardwareTypeVal': 94,
    'HaveDimmer': true,
    'HaveGroupCmd': true,
    'HaveTimeout': false,
    'ID': '00158d0001ab2357',
    'Image': 'Light',
    'InternalState': 'Closed',
    'IsSubDevice': false,
    'LastUpdate': '2019-04-06 12:40:06',
    'Level': 0,
    'LevelInt': 0,
    'MaxDimLevel': 100,
    'Name': 'Zigate - Door-00158d0001ab2357-01',
    'Notifications': 'false',
    'PlanID': '0',
    'PlanIDs': [
      0
    ],
    'Protected': false,
    'ShowNotifications': true,
    'SignalLevel': 4,
    'Status': 'Closed',
    'StrParam1': '',
    'StrParam2': '',
    'SubType': 'Switch',
    'SwitchType': 'Door Contact',
    'SwitchTypeVal': 11,
    'Timers': 'false',
    'Type': 'Light/Switch',
    'TypeImg': 'door',
    'Unit': 10,
    'Used': 1,
    'UsedByCamera': false,
    'XOffset': '0',
    'YOffset': '0',
    'idx': '47'
  },
  {
    'AddjMulti': 1,
    'AddjMulti2': 1,
    'AddjValue': 0,
    'AddjValue2': 0,
    'BatteryLevel': 255,
    'Color': '',
    'CustomImage': 0,
    'Data': 'Off',
    'Description': '',
    'DimmerType': 'abs',
    'Favorite': 0,
    'HardwareID': 5,
    'HardwareName': 'Yeelight Controller',
    'HardwareType': 'YeeLight LED',
    'HardwareTypeVal': 91,
    'HaveDimmer': true,
    'HaveGroupCmd': false,
    'HaveTimeout': false,
    'ID': 'C0A80003',
    'Image': 'Light',
    'IsSubDevice': false,
    'LastUpdate': '2019-04-06 01:18:26',
    'Level': 80,
    'LevelInt': 80,
    'MaxDimLevel': 100,
    'Name': 'Living Room Window',
    'Notifications': 'false',
    'PlanID': '0',
    'PlanIDs': [
      0
    ],
    'Protected': false,
    'ShowNotifications': true,
    'SignalLevel': '-',
    'Status': 'Off',
    'StrParam1': '',
    'StrParam2': '',
    'SubType': 'RGBWW',
    'SwitchType': 'Dimmer',
    'SwitchTypeVal': 7,
    'Timers': 'false',
    'Type': 'Color Switch',
    'TypeImg': 'dimmer',
    'Unit': 0,
    'Used': 1,
    'UsedByCamera': false,
    'XOffset': '0',
    'YOffset': '0',
    'idx': '48'
  },
  {
    'AddjMulti': 1,
    'AddjMulti2': 1,
    'AddjValue': 0,
    'AddjValue2': 0,
    'BatteryLevel': 255,
    'Color': '',
    'CustomImage': 0,
    'Data': 'Off',
    'Description': '',
    'DimmerType': 'abs',
    'Favorite': 0,
    'HardwareID': 5,
    'HardwareName': 'Yeelight Controller',
    'HardwareType': 'YeeLight LED',
    'HardwareTypeVal': 91,
    'HaveDimmer': true,
    'HaveGroupCmd': false,
    'HaveTimeout': false,
    'ID': 'C0A80002',
    'Image': 'Light',
    'IsSubDevice': false,
    'LastUpdate': '2019-04-06 01:18:27',
    'Level': 14,
    'LevelInt': 14,
    'MaxDimLevel': 100,
    'Name': 'Dining Room',
    'Notifications': 'false',
    'PlanID': '0',
    'PlanIDs': [
      0
    ],
    'Protected': false,
    'ShowNotifications': true,
    'SignalLevel': '-',
    'Status': 'Off',
    'StrParam1': '',
    'StrParam2': '',
    'SubType': 'RGBWW',
    'SwitchType': 'Dimmer',
    'SwitchTypeVal': 7,
    'Timers': 'false',
    'Type': 'Color Switch',
    'TypeImg': 'dimmer',
    'Unit': 0,
    'Used': 1,
    'UsedByCamera': false,
    'XOffset': '0',
    'YOffset': '0',
    'idx': '49'
  },
  {
    'AddjMulti': 1,
    'AddjMulti2': 1,
    'AddjValue': 0,
    'AddjValue2': 0,
    'BatteryLevel': 255,
    'Color': '',
    'CustomImage': 0,
    'Data': 'Off',
    'Description': '',
    'DimmerType': 'abs',
    'Favorite': 0,
    'HardwareID': 5,
    'HardwareName': 'Yeelight Controller',
    'HardwareType': 'YeeLight LED',
    'HardwareTypeVal': 91,
    'HaveDimmer': true,
    'HaveGroupCmd': false,
    'HaveTimeout': false,
    'ID': 'C0A8000B',
    'Image': 'Light',
    'IsSubDevice': false,
    'LastUpdate': '2019-04-06 01:18:26',
    'Level': 11,
    'LevelInt': 11,
    'MaxDimLevel': 100,
    'Name': 'Living Room',
    'Notifications': 'false',
    'PlanID': '0',
    'PlanIDs': [
      0
    ],
    'Protected': false,
    'ShowNotifications': true,
    'SignalLevel': '-',
    'Status': 'Off',
    'StrParam1': '',
    'StrParam2': '',
    'SubType': 'RGBWW',
    'SwitchType': 'Dimmer',
    'SwitchTypeVal': 7,
    'Timers': 'false',
    'Type': 'Color Switch',
    'TypeImg': 'dimmer',
    'Unit': 0,
    'Used': 1,
    'UsedByCamera': false,
    'XOffset': '0',
    'YOffset': '0',
    'idx': '50'
  }
];
